"""GitLab MR comment formatter for code review results."""

from shield_pr.formatters.base import BaseFormatter
from shield_pr.models.finding import Finding
from shield_pr.models.review_result import ReviewResult


class GitLabFormatter(BaseFormatter):
    """Format review results for GitLab MR comments.

    Uses GitLab-flavored Markdown with tables and checkboxes.
    Similar to GitHub but with GitLab-specific syntax differences.
    """

    def format(self, result: ReviewResult) -> str:
        """Transform ReviewResult to GitLab MR comment format.

        Args:
            result: ReviewResult containing findings and metadata

        Returns:
            Formatted GitLab MR comment Markdown
        """
        sections = [
            self._header(result),
            self._summary_table(result),
            self._findings_sections(result),
            self._footer(result),
        ]
        return "\n\n".join(filter(None, sections))

    def _header(self, result: ReviewResult) -> str:
        """Generate header with review badge.

        Args:
            result: ReviewResult with metadata

        Returns:
            Header Markdown string
        """
        return "## 🔍 ShieldPR\n\n*Generated by ShieldPR CLI*"

    def _summary_table(self, result: ReviewResult) -> str:
        """Generate summary table with key metrics.

        Args:
            result: ReviewResult with metadata

        Returns:
            Summary table Markdown
        """
        counts = self._count_by_severity(result)
        total = len(result.findings)
        confidence_pct = result.confidence * 100

        return (
            f"| Metric | Value |\n"
            f"|--------|-------|\n"
            f"| Platform | {result.platform} |\n"
            f"| Files Analyzed | {self._count_files(result)} |\n"
            f"| Issues Found | {total} |\n"
            f"| Confidence | {confidence_pct:.0f}% |\n"
            f"| :red_circle: High | {counts['HIGH']} |\n"
            f"| :yellow_circle: Medium | {counts['MEDIUM']} |\n"
            f"| :green_circle: Low | {counts['LOW']} |"
        )

    def _count_files(self, result: ReviewResult) -> int:
        """Count unique files in findings.

        Args:
            result: ReviewResult with findings

        Returns:
            Number of unique files
        """
        files = set()
        for finding in result.findings:
            files.add(finding.file_path)
        return len(files)

    def _findings_sections(self, result: ReviewResult) -> str:
        """Generate findings sections by severity.

        Args:
            result: ReviewResult with findings

        Returns:
            Findings sections Markdown
        """
        groups = self._group_by_severity(result)
        sections = []

        if groups["HIGH"]:
            sections.append(self._findings_section(
                groups["HIGH"],
                "High Priority",
                "HIGH"
            ))

        if groups["MEDIUM"]:
            sections.append(self._findings_section(
                groups["MEDIUM"],
                "Medium Priority",
                "MEDIUM"
            ))

        if groups["LOW"]:
            sections.append(self._findings_section(
                groups["LOW"],
                "Low Priority",
                "LOW"
            ))

        if not sections:
            return "### ✅ No Issues Found\n\nGreat job! No issues detected."

        return "\n\n".join(sections)

    def _findings_section(
        self,
        findings: list[Finding],
        title: str,
        severity: str
    ) -> str:
        """Generate findings section.

        Args:
            findings: List of findings
            title: Section title
            severity: Severity level for styling

        Returns:
            Findings section Markdown
        """
        emoji = ":red_circle:" if severity == "HIGH" else (
            ":yellow_circle:" if severity == "MEDIUM" else ":green_circle:"
        )

        lines = [f"### {emoji} {title} ({len(findings)})\n"]

        for finding in findings:
            location = self._format_location(finding)
            checkbox = "- [ ]" if severity == "HIGH" else "-"

            lines.append(
                f"{checkbox} **{finding.category}**: {finding.description}"
            )
            lines.append(f"  - 📍 *{location}*")

            if finding.suggestion:
                lines.append(f"  - 💡 {finding.suggestion}")

            if finding.code_snippet:
                lines.append(f"  ```")
                for line in finding.code_snippet.strip().split("\n"):
                    lines.append(f"  {line}")
                lines.append(f"  ```")

            lines.append("")

        return "\n".join(lines)

    def _format_location(self, finding: Finding) -> str:
        """Format file location with line number.

        Args:
            finding: Finding object

        Returns:
            Formatted location string
        """
        if finding.line_number:
            return f"`{finding.file_path}:{finding.line_number}`"
        return f"`{finding.file_path}`"

    def _footer(self, result: ReviewResult) -> str:
        """Generate footer with summary.

        Args:
            result: ReviewResult with summary

        Returns:
            Footer Markdown string
        """
        footer_lines = ["---"]

        if result.summary:
            footer_lines.append(f"\n**Summary**: {result.summary}")

        footer_lines.append(
            "\n*Report generated by [ShieldPR]"
            "(https://github.com/kietnguyenvulcanlabs/shield-pr)*"
        )

        return "\n".join(footer_lines)
